name: Generate Go SDK and publishing package

on:
  push:
    branches:
      -  main
    paths:
      - 'version_files/go.txt'
  
env:
   TOKEN: ${secrets.sdk}
   
jobs:
  generate_and_add_sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli@latest
      
      - name: Configure Git for SDK
        run: |
          git config --global user.email "ishaaidayatullah19@siesgst.ac.in"
          git config --global user.name "Ishaa-23"

      - name: Delete Existing SDK
        run: |
             rm -rf ${{ github.workspace }}/gosdk/*
            
      - name: Committing
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Delete GOSDK folder content"
            git push origin main
          else
            echo "No changes to commit."
          fi
      
    
      - name: Generate GO-SDK
        run: |
          openapi-generator-cli generate --verbose -i combined.yaml -g go -o ${{ github.workspace }}/gosdk --package-name EmployeeAPI 
          
      - name: Committing
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Committing Go sdk to folder"
            git push origin main
          else
            echo "No changes to commit."
          fi
     
        
      - name: Delete go.mod
        run: |
          rm -f ${{ github.workspace }}/gosdk/go.mod
          cd gosdk
          go mod init github.com/Ishaa-23/Go-Package
         
             
      - name: Committing
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Renaming github generic"
            git push origin main
          else
            echo "No changes to commit."
          fi
    
      - name: Push code to Go-Package
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.sdk }}
        with:
          source-directory: 'gosdk'
          destination-github-username: 'Ishaa-23'
          destination-repository-name: 'Go-Package'
          user-email: 'ishaaidayatullah19@siesgst.ac.in'
          target-branch: 'main'
          create-target-branch-if-needed: true
      
      - name: Create and push tags
        run: |
          version=$(cat version_files/go.txt)
          cd gosdk
          git tag -a $version -m "Releasing latest version"
          git push origin --tags
     
      
